### ISSUE TITLE
Python Not Working in Fiji

### ISSUE THREAD

**Issue by sunni426** [tkataras/Automatic-Cell-Counting-with-TWS#68]
Hello, thanks so much for the wonderful work! 

I am trying to run the ACCT plugin on FIJI, but I am encountering the log error "Cannot run program "python": error=2, No such file or directory." I am using a Python 3.11 version, and the python is on my bash path. I tried to install the most updated version of FIJI, but the ACCT plugins are not included. Do you know how I may solve this issue?

Thank you so much.

**Comment by TylerJang** [comment]
Hi,

From the details provided in the message, I think that maybe you didn't move the ACCT files:
```
ACCT_1.ijm
ACCT_2.ijm
ACCT_3.ijm
apply_BS_TWS_prob.bsh
apply_TWS_one_classifier_prob.bsh

```
into wherever you installed the newest version of Fiji. This is described in the bottom of the installation guide. There may be something else of course, so let me know if there are other details I can help with. If it is already there, then I would guess that when you select the path in ACCT_1, you may have selected the wrong folder since the error message implies that ACCT_1.ijm couldn't find a python file by that name. In running ACCT, you want to select the folder that says scripts_for_auto_cell_count.

I hope this helps :)

**Comment by TylerJang** [comment]
Marking as resolved due to time
